class OptionsState(object):
    NOT_INITIALIZED = "NOT_INITIALIZED"
    NOT_POPULATED = "NOT_POPULATED"
    POPULATED_NOT_OVERRIDDEN = "POPULATED_NOT_OVERRIDDEN"
    POPULATED_OVERRIDDEN = "POPULATED"
